services:
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@postgres.pl"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "80:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
  db:
    image: postgres:17.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: "zhp_generator"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pgadmin:
  pg: